# Generated by Django 4.1.7 on 2023-05-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_hotel_agent_alter_hotel_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.agent'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.person'),
        ),
    ]
