# Generated by Django 4.1.7 on 2023-05-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_hotel_agent_alter_hotel_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default=1, upload_to='static'),
        ),
    ]
