# Generated by Django 4.1.7 on 2023-05-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_hotel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='person',
        ),
        migrations.AddField(
            model_name='hotel',
            name='person',
            field=models.ManyToManyField(blank=True, null=True, to='home.person'),
        ),
    ]
