# Generated by Django 4.1.7 on 2023-05-12 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_hotel_person_hotel_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleType', models.CharField(max_length=100)),
                ('image', models.ImageField(default=1, upload_to='static')),
                ('number', models.CharField(max_length=100)),
                ('rent', models.IntegerField(default=0)),
                ('company', models.CharField(max_length=100)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.agent')),
                ('person', models.ManyToManyField(blank=True, null=True, to='home.person')),
            ],
        ),
    ]
